project:
  type: website

website:
  title: "SM25-student"
  navbar:
    right:
      - href: index.html
        text: Home
      - href: getting_started.qmd
        text: Installing
format:
  html:
    theme:
      - lumen
    css: styles.css



